### PR TITLE
Migrate to angular 6.0.1 and Rxjs 6.1.0

### PR DESCRIPTION
**Pull request by arnaudleclerc**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Migration to angular 6.0.1 and Rxjs 6.1.0

* **What is the current behavior?** (You can also link to an open issue here)

https://github.com/ObaidUrRehman/ng-drag-drop/issues/132

* **What is the new behavior (if this is a feature change)?**

### CODE REVIEW

**Comment by Supamiu** [comment]
Travis build failed due to a strange timeout while fetching some dependencies.

Nice PR 👍 I was about to do the same as removing rxjs-compat is a top priority for a lot of people right now (including me).

**Comment by arnaudleclerc** [comment]
@Supamiu Thanks! Should I do anything concerning the Travis build or should I wait for anyone to restart it if possible ?

**Comment by Supamiu** [comment]
I think @ObaidUrRehman should restart the build, or test the build by him/herself, just to make sure everything is going fine.

**Comment by ObaidUrRehman** [comment]
@arnaudleclerc, Thanks for this PR.
I remember fixing the Travis issue in master. I forgot to merge it into develop. Anyway, I will take care of it in a few hours.

**Comment by arnaudleclerc** [comment]
@ObaidUrRehman I managed to start the demo app without the angular-cli. I'll take a look at it and let you know. Thanks for the merge!

**Pull request merged**
